name: CI/CD pipeline
on:
  push:
    branches: [main]

jobs:
  test-app: 
    runs-on: ubuntu:latest

    steps: 
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install requirements
      uses: pip install -r requirements

    - name: Test file
      uses: pytest test.py -v 
